runtime: nodejs20
env: standard
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1   # ggf. 2, wenn Trafficspitzen

env_variables:
  PORT: 3000
  DEBUG_LOGGING: 1
  JWT_SECRET: "{<w8.&n9F+TgEC6T2?2rxK68,$&a&qs5"
  SENDGRID_API_KEY: "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"
  VERIFIED_SENDER_EMAIL: "noreply@kiermeyer.work"
  FRONTEND_URL: "http://localhost:5000"
  CLOUDINARY_CLOUD_NAME: "dveehdj7n"
  CLOUDINARY_API_SECRET: "AZyS15KcMquTk-QkRrc-NXC2h6g"
  CLOUDINARY_API_KEY: "871969675288917"
  CLOUDINARY_URL: "cloudinary://871969675288917:AZyS15KcMquTk-QkRrc-NXC2h6g@dveehdj7n"